package telas;

import controlador.ControladorJogo;

public class Jogo extends javax.swing.JFrame {
    ControladorJogo controlador;
    
    public Jogo(ControladorJogo ctr) {
        initComponents();
        controlador = ctr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_jogar = new javax.swing.JButton();
        btn_desistir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_frente = new javax.swing.JButton();
        btn_tras = new javax.swing.JButton();
        btn_direita = new javax.swing.JButton();
        btn_esquerda = new javax.swing.JButton();
        jpn_game = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snake - Partida");

        btn_jogar.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btn_jogar.setText("Continuar");
        btn_jogar.setName("btn_jogar"); // NOI18N

        btn_desistir.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btn_desistir.setText("Desistir");
        btn_desistir.setName("btn_desistir"); // NOI18N

        btn_sair.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setName("btn_sair"); // NOI18N
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_frente.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_frente.setText("↑");
        btn_frente.setAlignmentY(0.0F);
        btn_frente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_frente.setName("btn_frente"); // NOI18N

        btn_tras.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_tras.setText("↓");
        btn_tras.setAlignmentY(0.0F);
        btn_tras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tras.setName("btn_tras"); // NOI18N

        btn_direita.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_direita.setText("→");
        btn_direita.setAlignmentY(0.0F);
        btn_direita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_direita.setName("btn_direita"); // NOI18N

        btn_esquerda.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        btn_esquerda.setText("←");
        btn_esquerda.setAlignmentY(0.0F);
        btn_esquerda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_esquerda.setName("btn_esquerda"); // NOI18N

        jpn_game.setName("jpn_game"); // NOI18N
        jpn_game.setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout jpn_gameLayout = new javax.swing.GroupLayout(jpn_game);
        jpn_game.setLayout(jpn_gameLayout);
        jpn_gameLayout.setHorizontalGroup(
            jpn_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jpn_gameLayout.setVerticalGroup(
            jpn_gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        lbl_titulo.setFont(new java.awt.Font("Consolas", 1, 68)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Snake");

        lbl_nome.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        lbl_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nome.setText("Olá, jogador!");
        lbl_nome.setName("lbl_nome"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpn_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_frente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_tras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_direita, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_desistir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_jogar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpn_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_jogar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_desistir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_frente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_direita, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        controlador.finalizarTelaJogo();
    }//GEN-LAST:event_btn_sairActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desistir;
    private javax.swing.JButton btn_direita;
    private javax.swing.JButton btn_esquerda;
    private javax.swing.JButton btn_frente;
    private javax.swing.JButton btn_jogar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_tras;
    private javax.swing.JPanel jpn_game;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
